## NumPY


- it concists of the homogenous data type
- there is pre compiled C code for numpy
- it is the concept use to implement arrays and matrices
- variuos methematical,statistical,logical and some other useful functions

In [1]:
import numpy as np

In [19]:
ls = [i for i in range(1,99)]
arr = np.array(ls,dtype=float)
arr = np.asarray(ls,dtype=float)
print(arr)
#now lets check the dimensions of our array 
print("Dimensios")
print(arr.shape)
#it has got 98 rows
#lets say we want to have a 2 dimensional array
a = [1,2,3,4,5]
b = [6,7,8,9,10]
c = [11,12,13,14,15]
arr1 = np.array([a,b,c])
print("Array data")
print(arr1)
print("Dimensios")
print(arr1.shape)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53. 54.
 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71. 72.
 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89. 90.
 91. 92. 93. 94. 95. 96. 97. 98.]
Dimensios
(98,)
Array data
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Dimensios
(3, 5)


In [27]:
#now lets say we want to create an array with 0's , 1's or any Value n's
zeroes = np.zeros((5,5))
print("Zeroes")
print(zeroes)

ones = np.ones((5,5))
print("Ones")
print(ones)

n_value = np.full((5,5),3.1,dtype = float)
print("n_value")
print(n_value)

#lets say we want to have an identity matrix which has 1's at the diagnols and it has dimensions rows = columns
identity = np.eye(5)
print("Identity")
print(identity)

Zeroes
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Ones
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
n_value
[[3.1 3.1 3.1 3.1 3.1]
 [3.1 3.1 3.1 3.1 3.1]
 [3.1 3.1 3.1 3.1 3.1]
 [3.1 3.1 3.1 3.1 3.1]
 [3.1 3.1 3.1 3.1 3.1]]
Identity
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [38]:
random_array_float = np.random.random((5,3))
print("Random Float Array with 0-1 range")
print(random_array_float)

random_array_int = np.random.randint(1,99,(5,3))
print("Random int Array with 1-99 range")
print(random_array_int)

Random Float Array with 0-1 range
[[0.28559272 0.28267494 0.34446016]
 [0.62445154 0.91995898 0.18774183]
 [0.82045774 0.20440794 0.56382984]
 [0.43100418 0.82276258 0.27623605]
 [0.43210834 0.66124596 0.90862416]]
Random int Array with 1-99 range
[[21 36 85]
 [95 66 56]
 [94 41 14]
 [21 26 20]
 [ 8 71 14]]


In [47]:
#slicing of an array
print(random_array_int[0])
print(random_array_int[0][0])
print(random_array_int[:,0])
print(random_array_int[0,:])
print(random_array_int[0:3,0:2])

[21 36 85]
21
[21 95 94 21  8]
[21 36 85]
[[21 36]
 [95 66]
 [94 41]]


In [61]:
#uniform distribution and spacing
arr = np.linspace(0,2*np.pi,20)
arr1 = np.arange(0,10,1)
print("Linespace")
print(arr)
print("Arange")
print(arr1)

#to check the numbe of elements 
# print(len(arr))
# print(arr.size)

print("Datatype")
print(arr.dtype)


Linespace
[0.         0.33069396 0.66138793 0.99208189 1.32277585 1.65346982
 1.98416378 2.31485774 2.64555171 2.97624567 3.30693964 3.6376336
 3.96832756 4.29902153 4.62971549 4.96040945 5.29110342 5.62179738
 5.95249134 6.28318531]
Arange
[0 1 2 3 4 5 6 7 8 9]
Datatype
float64


In [66]:
#mathematical opeartions 
arr1 = np.random.randint(3,33,(4,4))
arr2 = np.random.randint(3,33,(4,4))

print(arr1+arr2)
print(arr1*arr2)
print(arr1-arr2)
print(arr1/arr2)

[[16 42 57 39]
 [17 30 31 24]
 [36 21 38 50]
 [33 34 36 22]]
[[ 55 377 806 248]
 [ 60 161 240 143]
 [288  80 297 589]
 [162 225 180  85]]
[[  6 -16   5  23]
 [ -7  16  -1  -2]
 [ 12 -11 -16  12]
 [ 21  16 -24 -12]]
[[2.2        0.44827586 1.19230769 3.875     ]
 [0.41666667 3.28571429 0.9375     0.84615385]
 [2.         0.3125     0.40740741 1.63157895]
 [4.5        2.77777778 0.2        0.29411765]]
